### ISSUE TITLE
在vuejs中的使用

### ISSUE THREAD

**Issue by dayney** [AppianZ/multi-picker#1]
在vuejs中使用，每次进到使用这个组件的页面就会自动跳转到地方去

**Comment by AppianZ** [comment]
自动跳转到地方去？

**Comment by dayney** [comment]
现在在ready里面使用，就没有这个问题，目前在chrom模拟器中没有问题，但是实体机器上有问题。在IOS上，选好的年没有月（目前只需要有年／月）。

**Comment by AppianZ** [comment]
你更新一下我的代码。

**Comment by dayney** [comment]
已经给你发邮件了，你看看。
