### ISSUE TITLE
multi-picker三级联动的问题

### ISSUE THREAD

**Issue by scorpionZK** [AppianZ/multi-picker#11]
我想问下一使用该插件做地址三级联动的时候，选择完能不能获取到地址的id，比如说北京对应的id为1，西城区对应的id为10，陶然亭对应的id为101，那么”北京西城区陶然亭“获取对应的三个id值，1，10，101？

**Comment by AppianZ** [comment]
可以的，演示demo里面有把回调返回的值都输出在页面上，你可以试试。然后可以在回调中构造你想要的数据格式

**Comment by scorpionZK** [comment]
好的，我已经找到了！插件非常好用，感谢开源，非常赞😊

**Comment by AppianZ** [comment]
不客气
