### ISSUE TITLE
支持数据重置吗？支持多次赋值吗？

### ISSUE THREAD

**Issue by nicole520** [AppianZ/multi-picker#12]
hi，妹纸
这个是否支持数据动态加载，比如第一次加载是2列，第二次加载是3列，或者是其它数据重置。因为jquery weui 好像不支持数据重置
是否支持多次赋值。因为jquery weui 遇到个问题就只能赋值一次，初始化的赋值才有效

**Comment by AppianZ** [comment]
我没太理解你的意思，但是我的插件本来就是可以一下子2列一下子3列的，你可以看看城市选择器那里，有的是三级联动，有的是五级联动，都可以自适应的

**Comment by nicole520** [comment]
以你的demo为例，比如，我打开页面，点击input，弹出picker。默认显示上海-徐汇区，这个能支持吗？ @AppianZ

**Comment by AppianZ** [comment]
这个暂时不支持，这个功能还没加进去
