### ISSUE TITLE
DateSelector.js的186行，当前时间应该是小于等于截止时间，不是小于截止时间

### ISSUE THREAD

**Issue by xiyan1120** [AppianZ/multi-picker#15]
185行：    rt > et ? alert('当前时间超过结束时间') : "";
186行：    return (bt <= rt && rt < et);

186行应该修改为：return (bt <= rt && rt <= et);
否则，两个时间相等的话，则会报错。

**Comment by AppianZ** [comment]
很早之前就修改过了哈，你的代码应该不是最新吧？

**Comment by xiyan1120** [comment]
好，谢谢啊。话说区域选择的，建议你可以添加一个打开显示默认值的。
我有fork了一个版本，添加了区域选择器显示时的默认值，而且，我也添加了非移动端能操作的事件。

**Comment by AppianZ** [comment]
恩，很多人都这么建议我了哈，有时间我会加上这个功能的，谢谢
