### ISSUE TITLE
请问支持vue2.0吗？

### ISSUE THREAD

**Issue by summer-yyyn** [AppianZ/multi-picker#16]
请问支持vue2.0吗？

**Comment by AppianZ** [comment]
这是原生插件，适用于任何框架哦

**Comment by goodLucky-J** [comment]
在安卓表现完美，在ios显示得小了一点，改scss变量貌似不行，会选择不正确，有简单解决办法吗？

**Comment by AppianZ** [comment]
在你修改scss的高度的时候，记得修改js里面的liheight。只要修改这两个参数，其他都是自动计算的
