### ISSUE TITLE
about the MultiPicker 

### ISSUE THREAD

**Issue by ry836478606** [AppianZ/multi-picker#18]
if i get one data of the city.js, i want to let the input show the data's value and input selector can scroll
to the right place. How can i do this.

**Comment by AppianZ** [comment]
这个功能暂时没提供

**Comment by ry836478606** [comment]
那应该怎么改比较好，刚刚开始还以为是老外呢

**Comment by ry836478606** [comment]
你也在厦门吗，，能加一下你的微信请教吗
