### ISSUE TITLE
希望可以支持ES6 modules或者CommonJS格式引用

### ISSUE THREAD

**Issue by jrainlau** [AppianZ/multi-picker#2]
非常棒的项目！但是目前暂时只能通过`<script></script>`的格式引用，在开发中非常不方便，希望可以支持ES6 modules或者CommonJS格式引用，谢谢！

**Comment by AppianZ** [comment]
感谢支持，正在逐步完善中

**Comment by jrainlau** [comment]
[MultiPicker.txt](https://github.com/AppianZ/multi-picker/files/608178/MultiPicker.txt)
直接帮你弄了一份了，es6模块版本的。

**Comment by xvinc** [comment]
Handling of 'touchstart' input event was delayed for 2881 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by AppianZ** [comment]
I updated it last night

**Comment by zzl1991** [comment]
搞得不错，好好干
