### ISSUE TITLE
a little problem in a long page when it is scrolling

### ISSUE THREAD

**Issue by Iamxiaozhu** [AppianZ/multi-picker#21]
The input is triggered by the method 'touchstart',so in a long page,it will be triggered immediately when you scroll the page , it is more like mis-trigger.

**Comment by AppianZ** [comment]
你的target-input的点击范围很大吗？

**Comment by Iamxiaozhu** [comment]
并不是input范围很大,页面中用到了比较多的选择器,页面内容比较多,需要滚动,每次滚动按到input就会弹出选择框,不过问题已经解决了
