### ISSUE TITLE
默认显示

### ISSUE THREAD

**Issue by kunjingzhu** [AppianZ/multi-picker#27]
当我默认显示[日，时，分]，
 param : [0,0,1,1,1],
beginTime，endTime，数组里面只能设置三个值。
beginTime，endTime跨月设置的时候会报错。
当前是时间：2017-04-26 16:03
例如：beginTime, endTime数组元素只能写3个，写5个报错。
beginTime:[26,16,3] ,     endTime:[1,16,3];//五月1号会报错。

**Comment by AppianZ** [comment]
第一个问题：
“当我默认显示[日，时，分]，param : [0,0,1,1,1], beginTime，endTime，数组里面只能设置三个值。”
“例如：beginTime, endTime数组元素只能写3个，写5个报错。”
答：beginTime中的值与param中为1的对应，所以肯定只能有三个。

第二个问题：
“beginTime:[26,16,3] , endTime:[1,16,3];//五月1号会报错。”
答：既然你只设置了日期，那么肯定是当前月的日期，你这个设置的时间范围是【2017-04-26 16:03 ~ 2017-04-01 16:03】，所以报错。

第三个问题：
“beginTime，endTime跨月设置的时候会报错。”
答：如果你要跨月param : [0,1,1,1,1],
