### ISSUE TITLE
年月日 时分的切换可以写成 开始时间 结束时间的切换吗

### ISSUE THREAD

**Issue by amazingHuo** [AppianZ/multi-picker#28]
![_20170507231014](https://cloud.githubusercontent.com/assets/17975200/25782303/82b015d0-337a-11e7-9595-ac929367c4eb.png)

**Comment by amazingHuo** [comment]
问题比较着急 如果可以微信及时联系 那就太感谢啦 微信：18754381731 Yo man

**Comment by amazingHuo** [comment]
thanks again

**Comment by AppianZ** [comment]
请认真阅读文档。这是一个【年月日时分】五级联动，为了美观需要所以用tab左右切换展示。如果你有两个时间需要选择，可以new 两个实例分别选择

**Comment by amazingHuo** [comment]
嗯嗯，看来只能new 两个啦
