### ISSUE TITLE
嘉宝嘉宝 请教一个样式问题

### ISSUE THREAD

**Issue by jameschopin** [AppianZ/multi-picker#29]
如果遇到什么神bug,不要着急。这时候,请对我发起issue~ 一定让您满意！
我是嘉宝Appian，一个卖萌出家的算法妹纸。
Trust Me. Again.

看到这个进来的 是这样的 滑动速度太快 在手机上样式 比如滑动省 由于联动的效果 区有时候加载到一起了 就变黑了  怎么把这个速度设置慢一点 等待你的回答！！！！很急

**Comment by AppianZ** [comment]
没有~

**Comment by AppianZ** [comment]
没有接口给你设置速度，你可以去改源码

**Comment by jameschopin** [comment]
恩 我找了2天了 现在去调那个速度 css 3有个属性transition-duration 改了也没用!!!!! 很绝望啊！！！

**Comment by AppianZ** [comment]
”区有时候加载到一起了“ 是什么意思，你把你的数据贴一下

**Comment by jameschopin** [comment]
是这样的 我的控件是city-picker 发现好像都是用的这个 然后他引的是 ion-multi-picker/  好像都是一样的速度 为了保证数据一致性 他的接口是这样的一个数组[province,children:{child}]可以理解成一个三维吧...然后 数据是一次请求的 之前是三个接口  现在Push进省的数组去了 然后手机滑动很快 就导致市区 有时候根本看不清楚 或者第一次加载的时候就是黑的 数据是我们公司自己接口的 要请求需要vpn 就是普通的城市接口 你可以down那个代码 到手机看是一样的效果~~~~~ 囧 好烦

**Comment by AppianZ** [comment]
每次省份切换一定会导致重绘，如果重绘之前数据不能准备好，肯定会重绘失败。确实挺多人用的。但都没什么问题，因为数据没问题。我自己用的时候有时候是五级联动都不会出现什么问题。

总之，在实例化之前确定你的数据正确

**Comment by jameschopin** [comment]
确实不是数据的问题 我一直在说的是体验 省份加载是左滑式的 因为滑的太快 导致数据还在加载 对。。感觉有可能是这个的问题 因为三次请求 但是现在把它封道了一个list里面去了 所有的数据应该都是一次加载的 想找样式 无从下手 开早会说了下这个问题 先抛出来 做底下的需求吧 谢谢你了！

**Comment by AppianZ** [comment]
如果遇到你这样的数据问题，那么前端样式设计就不能采用这样的多级联动设计，应该换做京东的那种城市级联。因为渲染重绘的速度绝对是比请求来的快的，所以这的样式设计是只能满足数据一开始就准备好的情况，如果需要动态加载，还是模仿京东的城市级联比较好，即使是京东的城市级联，级联过程中还有loading呢，所以说明动态加载的耗时肯定是比重绘来的快的，出现这种问题的时候，就需要重新设计一个插件了。
