### ISSUE TITLE
请问有react里使用的经验么？

### ISSUE THREAD

**Issue by Mr-Kapok** [AppianZ/multi-picker#32]
![image](https://cloud.githubusercontent.com/assets/13746070/26194393/d44154ea-3bea-11e7-923f-021def8a180a.png)
![image](https://cloud.githubusercontent.com/assets/13746070/26194409/df8f06da-3bea-11e7-89a5-089fae5e9fd1.png)
获取到了id 还是报错

**Comment by Mr-Kapok** [comment]
抱歉  忘了加入 json 我的问题

**Comment by AppianZ** [comment]
哈哈哈哈
