### ISSUE TITLE
配合 flexble 样式问题

### ISSUE THREAD

**Issue by Mr-Kapok** [AppianZ/multi-picker#33]
嘉宝，我的布局用的是flexble，看了之前的issuer我修改了 line-height ,但是现在还是有问题，是还有哪些地方要改的？

css
$liHeight : 0.8rem; 

js
this.liHeight  = parseInt(doc.getElementsByTagName('HTML')[0].style.fontSize)*0.8;

在 肾6plus计算有问题，安卓下计算也是不怎么准确

**Comment by Mr-Kapok** [comment]
已解决，总结下需要做以下处理：
css:
1:修改.multi-picker-content & li 的font-size
2:修改.multi-picker-content的 top:$headHeight;
3:修改multi-picker-container 
   (1):height:($liHeight * 5 + $headHeight);;
   (2):translate3d(0,101%,0)；
js:
this.liHeight = parseInt(doc.getElementsByTagName('HTML')[0].style.fontSize)*0.8;
ps:0.8是scss中$liHeight 的rem值

**Comment by AppianZ** [comment]
感谢完善
