### ISSUE TITLE
发现一个BUG，ios点击弹出选择器后，ios原生的完成那一栏也会跟着弹出来。ios10.3.2

### ISSUE THREAD

**Issue by iherewy** [AppianZ/multi-picker#36]
两个选择器都有类似问题存在。

**Comment by AppianZ** [comment]
ios原生的完成

是什么？

**Comment by iherewy** [comment]
![image](https://cloud.githubusercontent.com/assets/13548748/26714037/18ad82b2-47a2-11e7-900b-ee249f4b8773.png)
这个会显示在底部

**Comment by AppianZ** [comment]
首先，这个东西的出现，是因为触发弹层的dom是input，你可以用任意dom替换这个input。

详见readme的常见问题。

**Comment by iherewy** [comment]
你的意思是这个不算BUG吗？
