### ISSUE TITLE
选择的dom下面不能有child元素是吧。否则就选择不了。

### ISSUE THREAD

**Issue by iherewy** [AppianZ/multi-picker#37]
rt

**Comment by prianyu** [comment]
我也遇到这个问题了，一般情况下可能有这种需求，就是一个表单列表里面有label，有i，有input,需求是需要点击整块，所有外层包含一个div，绑定在div上，这时就失效了。是代码了阻止了冒泡吧

**Comment by AppianZ** [comment]
是的
