### ISSUE TITLE
上拉菜单标题栏背景色为什么变成灰白色了？

### ISSUE THREAD

**Issue by acid122** [AppianZ/multi-picker#39]
嘉宝你好，很感谢你做出了这么好的一个框架，之前感觉手机端的日期选择还有自定义多级联框架不太好找的，在你这儿都给实现了：），我有个小问题是你之前demo演示的gif动图里面，点击日期后的上拉菜单中的确定、取消按钮所在的标题栏是比较醒目的蓝绿色，我个人觉得蛮好看的，但是现在我实际下载下来的最新项目中的颜色变成了灰白色，我觉得这个颜色识别度比较低，请问是有意为之吗，我除了覆盖你当前css设置外，能有其他方式使用之前的那套样式吗？

**Comment by AppianZ** [comment]
颜色自己控制就好，我是怕薄荷绿太扎眼，所以换成了灰白，你可以审查元素找到我的dom样式，直接覆盖。我之前的样式没留。
