### ISSUE TITLE
城市的json数据不利于维护

### ISSUE THREAD

**Issue by mumuy** [AppianZ/multi-picker#4]
当前使用的json不利于维护，按现在行政区划的变化，每个月都有一两个区的调整，数据很容易滞后……这也能造成用户不想用！

建议使用“行政区划代码”来管理这部分数据，可以参考我这个项目：https://github.com/mumuy/data_location

所有行政区划信息只需要区划代码和行政单位的键值对关系就好

**Comment by AppianZ** [comment]
json只是示例哈，如果用户有自己的需要，可以任意修改。目前我们自己产品在用的也是我们自己的json。谢谢大大的指教~~~哈哈哈

**Comment by mumuy** [comment]
还有一个问题哦，如何初始化选中状态呢？比如我用这个插件来做收货地址的选择，我得能让用户编辑呀，默认选择是他之前保存的地址。比如默认选中：福建省厦门市思明区

**Comment by AppianZ** [comment]
关于初始值的功能，会利用平时的课余时间补上~
