### ISSUE TITLE
DateSelector 改变了params参数,发现界面不重绘啊

### ISSUE THREAD

**Issue by salamander-mh** [AppianZ/multi-picker#47]
少年你还是得多加点能力啊,我又发现DateSelector中事件直接绑定到了document上,
造成了原来的监听绑定这,我都想哭了,以为这个库还是不错的......

**Comment by AppianZ** [comment]
请认真看文档哈，童鞋

**Comment by salamander-mh** [comment]
我需要的是动态改变的能力,譬如用户选择了只看年份的,那就切换到年份的,如果选择了年份和月份的,那就切换到那个样式,然后这个库现在并没有这个能力

**Comment by AppianZ** [comment]
调用的时候讲究技巧就可以做到，毕竟是原生的库，如果要配合市面上各种框架肯定不行，所以建议考虑开发自身配合的框架的生命周期，讲究调用技巧。

**Comment by salamander-mh** [comment]
我的技巧就是放两个DateSelector(这样很不优雅),不管怎么讲,库还是不错的

**Comment by AppianZ** [comment]
如果我的库没有实现你的需求，你也可以看看  https://github.com/AppianZ/multi-picker/blob/master/How_to_Build_it.md

这是整个库的实现过程，你可以把数据迭代实现的部分抄过去，丰富原型链上的方法，或者自己另外再开发一个轮子也可以，把你想要实现的实例调用方法实现出来，也不错。
