### ISSUE TITLE
同个页面可以实例化多个吗

### ISSUE THREAD

**Issue by shynee** [AppianZ/multi-picker#5]
`var json = [{id: '0', value: '女'},{id: '1', value: '男'}];`
`var picker1 = new MultiPicker({
            input : 'picker1-id',
            container : 'selectContainer',
            jsonData: json,
            success : function(arr){
                alert(arr);
            }
        });`
`var picker2 = new MultiPicker({
            input : 'picker2-id',
            container : 'selectContainer',
            jsonData: json,
            success : function(arr){
                alert(arr);
            }
        });`
这样picker1似乎就用不了了

**Comment by AppianZ** [comment]
container 要设置不同的dom的id哦。

**Comment by shynee** [comment]
原来如此，失礼了
