### ISSUE TITLE
在IOS下获取焦点软键盘 发现无法与其他input自动切换焦点 使得软键盘覆盖BUG

### ISSUE THREAD

**Issue by zhanjunhao** [AppianZ/multi-picker#54]
在IOS下获取焦点软键盘 发现无法与其他input自动切换焦点 使得软键盘覆盖BUG 求解决方案！！！

**Comment by AppianZ** [comment]
没看懂。。。截图？

**Comment by AppianZ** [comment]
另请仔细阅读文档

## 常见问题

### **3. 触发弹窗的dom一定要是input吗？**

在文档中明确指出，触发弹层的dom可以是任意的dom。并建议弹层的容器，是body的第一级子元素。

demo中使用了input disabled只是为了返回值可以通过设置value返回，演示方便。input readonly可能存在一些兼容问题.

开发者可以使用任意dom，将回调的返回值innerHTML或者双向绑定等。这里不再赘述。

**Comment by zhanjunhao** [comment]
已解决了 在多个输入框或文本域IOS真机下测试切换 获取焦点失去焦点异常！

**Comment by zhanjunhao** [comment]
![image](https://user-images.githubusercontent.com/25976993/29402882-28edd9c6-8369-11e7-92df-c7fa6e9beeec.png)

**Comment by AppianZ** [comment]
解决了就好，虽然还是不懂你说的是哪个插件。
