### ISSUE TITLE
关于样式的问题

### ISSUE THREAD

**Issue by CangJL** [AppianZ/multi-picker#57]
你好，不知道为什么弹出的选择器样式是乱的，字体大小也不对，蜷缩在一起。一开始以为是引用的bootstrap问题，然后新建了一个html只引入了DateSelector的css和js。可是还是一样。就是弹出的样式是不正常的，很是奇怪，希望能帮忙解决一下，谢谢

![tim 20170907092751](https://user-images.githubusercontent.com/18461523/30141600-0a83db74-93af-11e7-8be4-7975e351edc7.png)

**Comment by AppianZ** [comment]
1. 请附上实例化的代码和使用的css版本
2. 检查HTML 是否被缩放
3. 是否所有手机打开都是出现样式问题

**Comment by AppianZ** [comment]
4. 用出现样式问题的手机打开我的demo，会出现样式问题吗

**Comment by CangJL** [comment]
你好，问题解决了，但是过程异常离奇。先把你的DateSelector.css内容换成demo中的css内容，然后就正常了。接着再换回你原来的DateSelector.css，结果还是正常的。简直就是灵异事件，8天前提问的，这段时间里天天刷新清缓存都没用，结果今天替换了一下内容就好了。虽然demo中的css和DateSelector.css的内容是一模一样的...总而言之好了，谢谢

**Comment by AppianZ** [comment]
真是一个灵异的bug。没事了就好
