### ISSUE TITLE
在使用DateSelector时是否可增加自定义列

### ISSUE THREAD

**Issue by xzfd1010** [AppianZ/multi-picker#64]
进行身份证的有效日期校验时，因为有的身份证长期有效，希望能增加一列”长期“，请问是否有办法解决呢？

**Comment by AppianZ** [comment]
解决的方法有很多种。
1. 如果从产品的角度来改，你可以在你的页面中增加一个checkbox。如果是长期，就选择长期，如果不是长期，才弹出DateSelector来选择日期

2. 如果你想修改DateSelector，我想了解一下，增加列是想如何增加？这个“长期”是和“年/月/日”并列？ 还是想要在最后面添加？
不过就我的想象中，你想要修改源码去添加一个“长期”这个单项是做不到的

3. 如果你一定要在弹出层中添加一个“长期”，可以试试
https://github.com/AppianZ/multi-picker/tree/master/MultiPicker。
这个就是专门可以自定义滑动内容的，只不过连时间你都得自定义了，你得自己构造年月日的时间数组，然后传入，也可以解决

**Comment by xzfd1010** [comment]
好的，了解了，谢谢
