### ISSUE TITLE
与flexible.js的兼容问题

### ISSUE THREAD

**Issue by xzfd1010** [AppianZ/multi-picker#65]
使用插件之后发现很贴心的做了对flexible的兼容，非常感谢。
只是有一点小问题，在Android的某些机型上滚动时，有时候因为js的小数问题，计算出来的结果会是undefined。
![image](https://user-images.githubusercontent.com/15313636/32143921-2f81e5ee-bc7f-11e7-98f6-a98d86f28d7e.png)
经过调试发现是在这两句代码计算时出现了小数导致的。
```javascript
this.recent_time[realIdx] = Math.round(-targetLong / this.liHeight) + 1;
this.resultArr[checkIdx] = arr[Math.round(-targetLong / this.liHeight) + 2];
// 还有这里
var tempRes = that.end.index = Math.round(that.distance[idx] / that.liHeight) + 2;
```
目前加上取整后暂时没有再发现问题。
再次感谢您制作的控件。

**Comment by AppianZ** [comment]
thanks :)
