### ISSUE TITLE
多个实例的时候，除了第一个实例能操作，其他都会在正常操作时报错

### ISSUE THREAD

**Issue by shynee** [AppianZ/multi-picker#7]
具体的表现发了张GIF到你的sina邮箱

`MultiPicker.js:162 Uncaught TypeError: Cannot read property 'offsetHeight' of null(…)`
`(anonymous function) @ MultiPicker.js:162`
`loop @ MultiPicker.js:18`
`initReady @ MultiPicker.js:160`
`checkRange @ MultiPicker.js:208`
`touch @ MultiPicker.js:265`
`(anonymous function) @ MultiPicker.js:146`

`MultiPicker.js:76 Uncaught TypeError: Cannot use 'in' operator to search for 'child' in undefined(…)`
`checkArrDeep @ MultiPicker.js:76`
`initReady @ MultiPicker.js:117`
`checkRange @ MultiPicker.js:208`
`touch @ MultiPicker.js:265`
`(anonymous function) @ MultiPicker.js:146`

**Comment by AppianZ** [comment]
前天我有更新了一个地方的代码，你可以更新下看看

**Comment by AppianZ** [comment]
可以再次更新一下我的代码，刚刚又更新了一下~

**Comment by shynee** [comment]
Sorry，回复不及时，看到已经修复了，很棒
