### ISSUE TITLE
这个要是能修改成兼容PC的浏览器就好了

### ISSUE THREAD

**Issue by quzefeng** [AppianZ/multi-picker#76]
这个要是能修改成兼容PC的浏览器就好了，我们希望这个控件能在PC电脑上也能使用。否则在PC上显示的话，这个控件不能用，我们需要考虑如何做的问题。

**Comment by AppianZ** [comment]
pc 没有touch事件啦哈哈，所以说专门为移动端而生的。pc的话有很多现成的，移动端这种拆件比较少的
