### ISSUE TITLE
iphone输入框兼容问题

### ISSUE THREAD

**Issue by Fzhaoyang** [AppianZ/multi-picker#84]
你好，我引用了你的地区选择插件，在iPhone机上遇到兼容问题，输入框键盘不能自动关闭，挡住了地区选择的弹窗，请问你有可行的解决办法吗？可否加下QQ细聊，万分感谢！我的QQ号是2305613385

**Comment by AppianZ** [comment]
写一个假的按钮，比如div，p标签就好了，input框不是关注的重点啊。
